# Generated by Django 5.0.2 on 2024-05-20 08:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=300, null=True)),
                ('model_type', models.CharField(default='completion', max_length=50)),
                ('response_type', models.CharField(default='default', max_length=50)),
                ('engine', models.CharField(default='gpt-3.5-turbo-instruct', max_length=50)),
                ('n_epochs', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('batch_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('learning_rate_multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('compute_classification_metrics', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('finetune', models.TextField(blank=True, null=True)),
                ('preparation', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tuned_at', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupportTrainingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('completion', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('support_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_training_data', to='support_app.supportmodel')),
            ],
        ),
    ]
