# Generated by Django 4.2.3 on 2025-05-03 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportmodel',
            name='engine',
            field=models.CharField(default='gpt-3.5-turbo', max_length=50),
        ),
    ]
